### PR TITLE
Fixed some NPEs on the rendering thread

### PR DESCRIPTION
**Pull request by Stredox02**

### CODE REVIEW

**Comment by Khajiitos** [comment]
Does this crash ever actually happen? I know that the default values for fields in the LocationInfo class are null, maybe it'd be better if they had e.g. empty strings (or "unknown" for the country code) instead?

**Comment by Stredox02** [comment]
Yes, it happens when the Show District or Show ISP option is enabled. Eventually yeah we can put "unknown" instead of a null checking

**Comment by Stredox02** [comment]
[11:52:21] [Render thread/ERROR]:
 Reported exception thrown!
net.minecraft.util.crash.CrashException: Rendering screen
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:955) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1275) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[1.20.2-0.14.24.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.24.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "this.locationInfo.districtName" is null
	at me.khajiitos.servercountryflags.common.screen.ServerMapScreen$Point.getTooltip(ServerMapScreen.java:276) ~[servercountryflags-1.9.0-1.20.2-FABRIC.jar:?]
	at me.khajiitos.servercountryflags.common.screen.ServerMapScreen.render(ServerMapScreen.java:228) ~[servercountryflags-1.9.0-1.20.2-FABRIC.jar:?]
	at net.minecraft.client.gui.screen.Screen.renderWithTooltip(Screen.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:946) ~[client-intermediary.jar:?]
	... 6 more
	
	
	
I've had other problems with these options, you're probably right it's better to enter "unknown" or something like that instead.

**Comment by Khajiitos** [comment]
I will investigate this later, however I'm pretty sure the API sends an empty string for district name if it is not present. Do you get the crash when you hover over any flag, or only an unknown one? The 1.20.2 branch is on 1.9.0, and the 1.9.2 version available for older versions should fix crashing whem hovering over unknown flags.

**Comment by Stredox02** [comment]
I'm using the latest version of the mod and the last exception happens when I open the server map by clicking the icon in the multiplayer menu

**Comment by Khajiitos** [comment]
What's interesting is that I'm unable to reproduce the crash. Tried Fabric 1.20.2, spamming refresh with these options, entering and leaving the server map screen, never happens. The only way districtName or isp could be null is if the API result is not what we expected (https://github.com/Khajiitos/ServerCountryFlags/blob/1.20.2/Common/src/main/java/me/khajiitos/servercountryflags/common/util/LocationInfo.java#L21). Do you get any logs before the crash from that constructor?

**Comment by Stredox02** [comment]
Screenshot_2
Just tried

**Comment by Khajiitos** [comment]
Do you know if the API responds with {"status":"fail"} for your own IP address, or for a server's IP address? If so, does it also respond with a fail if you visit [http://ip-api.com/json/](http://ip-api.com/json/) in your browser? If it does, there might be an API bug.

**Comment by Stredox02** [comment]
I tried on chrome and the API response was successful.

**Comment by Khajiitos** [comment]
The API should technically never fail, would you be able to investigate which IP/URL made it fail, and if the fail is persistent?

**Comment by Stredox02** [comment]
Yeah exactly, I'll try to investigate, but I think these types of errors need to be handled anyway to avoid game crashes

**Comment by Stredox02** [comment]
I took the time to debug the problem, I found this:
image

it seems that the local IPS returns an error from ip-api.com

**Comment by Khajiitos** [comment]
That helps a lot! Does the error happen only when you have a server with 0.0.0.0 in the server list (or any other reserved address that the Java utility didn't catch), or not necessarily? (The mod also requests local location for calculating distances)

**Comment by Stredox02** [comment]
No, it only happens with 0.0.0.0, other local IPs are already checked

**Comment by Khajiitos** [comment]
Thanks!

**Pull request merged**
